theme = "onedark"

[editor]
clipboard-provider = "pasteboard"
default-yank-register = "+"
line-number = "absolute"

[editor.soft-wrap]
enable = true

[keys.normal.space.m]
p = ':sh "$HOME/dotfiles/bin/hx-glow-preview" "%{buffer_name}"'
