[[language]]
name = "python"
language-servers = ["ty"]

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
LongSentences = false
