#!/bin/bash
# Default config
path=~/workspace/swedbank/
portals=(fdp-portal-private fdp-portal-hybrid)
cd $path
for portal in ${portals[*]}; do
	echo portal: $portal
	scope=$(echo $portal | sed 's/\(.*\)-.*/\1/')
	echo App: $scope
	echo Downloading...
	
	case $scope in
		"fdp-portal")
    			area=fdppor
    		;;
		"fdp-app" | "fdp-util")
    			area=fdpap
    		;;
		*)
   			 area=" "
    		;;
	esac
	echo area: $area;
 	link=ssh://git@git.swedbank.net:7999/$area/$portal.git

	git clone $link
	cd $portal
	yarn install
	cd -	
done

#start private
start
