#!/bin/bash
#Set gitconfig
rm -f ~/.gitconfig
git config --global user.name "Paulius Kutka"
git config --global user.email "paulius.kutka@swedbank.lt"
git config --global url.ssh://git@git.swedbank.net:7999/.insteadOf https://git.swedbank.net/scm/
git config --global --add url.ssh://git@git.swedbank.net:7999/.insteadOf http://stash.sbcore.net:7990/scm/
git config --global http.proxy http://p998pfl:p998pfl@proxyvip.foreningssparbanken.se:8080/
git config --global http.sslVerify false
git config --global http.https://git.swedbank.net/.sslcainfo ~/swed/swedbank-root-ca.cer
git config --global http.https://git.swedbank.net/.sslVerify true
git config --global http.https://git.swedbank.net/.proxy "" 
git config --global http.http://stash.sbcore.net:7990/.sslcainfo ~/swed/swedbank-root-ca.cer
git config --global http.http://stash.sbcore.net:7990/.sslVerify false
git config --global http.http://stash.sbcore.net:7990/.proxy ""
git config --global core.askpass false
git config --global core.editor /usr/bin/vim
git config --global alias.ready "!git checkout integration; git pull; git checkout -"
git config --global alias.in 'checkout project/integration'
echo "Config done"
