#!/bin/bash
#Set gitconfig
rm -f ~/.gitconfig
git config --global user.name "Paulius Kutka"
git config --global user.email "paulius.kutka@swedbank.lt"
git config --global url.ssh://git@git.swedbank.net:7999/.insteadOf https://git.swedbank.net/scm/
echo "Config done"
