#!/bin/bash
domains=(www.facebook.com www.instagram.com www.linkedin.com www.reddit.com app.slack.com)
host_file=/etc/hosts
#sed -i '' '$d' ~/hosts
if grep -Fxq "#Blocked websites:" $host_file
then
     line=$(grep -n "#Blocked websites:" $host_file | cut -d: -f1)
     sed -i '' "${line}d" $host_file
     for domain in ${domains[*]}; do
        line=$(grep -n "$domain" $host_file | cut -d: -f1)
        sed -i '' "${line}d" $host_file
     done
     echo "You can relax now, m8"
else
    echo "Preparing work environment..."
    echo "#Blocked websites:" >> $host_file
    for domain in ${domains[*]}; do
	echo "127.0.0.1 $domain" >> $host_file
	echo "Added $domain"
    done
fi
