#!/usr/bin/env bash

CASKS=(
    firefox
    google-chrome
    slack
    virtualbox
    visual-studio-code
    lastpass
    hyper
    airtable
)

echo "Installing cask apps..."
#brew cask install ${CASKS[@]}

for cask in ${CASKS[@]}; do
    brew cask install $cask
done
